### ISSUE TITLE
widget options different from the documentation

### ISSUE THREAD

**Issue by chili-chiu** [haesleinhuepf/napari-assistant#10]
Opening the widget through Plugins > napari-assistant: Assistant resulted in the widget that only contains 3 search icons:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/89602983/162030459-11842c60-d29d-4382-9b0b-3921916cf9e7.png">
Quite different from the ones shown in the documentation. 

I also noticed this error that seems to interfere with the widget:
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

**napari info**
napari: 0.4.15
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.3
Python: 3.9.7 (default, Sep 16 2021, 08:50:36) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.12.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 ATI-4.8.13
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1792x1120, scale 2.0

Plugins:
- console: 0.0.4
- napari-assistant: 0.1.8
- napari-time-slicer: 0.4.3
- napari_skimage_regionprops1: 0.4.0
- napari_skimage_regionprops2: 0.4.0
- ndtiffs: 0.1.2
- scikit-image: 0.4.15
- svg: 0.1.5

**Comment by haesleinhuepf** [comment]
Hi @chili-chiu ,

thanks for reaching out! It appears the installation was not successful. I'm suspecting you installed napari-assistant standalone, which is not recommended. See the [installation instructions](https://github.com/haesleinhuepf/napari-assistant#installation). Background is: the assistant is just a user-interface for other plugins. It is recommended to install one of the [other](https://www.napari-hub.org/?search=napari-assistant&sort=relevance) plugins and then use it through the assistant.

Do you think, we should hide it from the napari-hub and/or from the list of plugins in the plugin installer? It might then also disappear from the plugins menu... 

I'm also curious about @neuromusic's opinion.

Thanks again!

Best,
Robert

**Comment by chili-chiu** [comment]
I should've read the installation instruction more carefully, my bad! I also missed (and didn't fully understand) what meta-plugins meant until now. 

The documentation visibility on napari hub is useful for others to be aware of what's available in the ecosystem. Being able to install them just like other plugins is a bit confusing - maybe we need a broader discussion on ways to handle these special types :)
