### ISSUE TITLE
Workflow loading: cluttering the overlay

### ISSUE THREAD

**Issue by Cryaaa** [haesleinhuepf/napari-assistant#2]
Everytime a workflow is loaded from disc all the widgets are added simultaneously filling up the widget panel to the righthand side. It could be better to only display the widget which generates the layer that is currently selected. Furthermore, the actual layout could be optimised to make the layout more visually pleasing.

**Comment by Cryaaa** [comment]
Would be closed by 11 once merged

**Comment by haesleinhuepf** [comment]
Let's close this once the PR is merged. You can write `closes #2` in the PR to automatically close this issue once the PR is merged.
